# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

# Run on all commits
# NOTE: can be changed later, as described in here:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on: push

jobs:
  build:
    # Pin to Ubuntu 22.04, see https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        find . -name "*.jar"
        md5sum code/extensions/asmeta.validator/asmeta.validator/dist/AsmetaV.jar
        wget https://nusmv.fbk.eu/distrib/NuSMV-2.6.0-linux64.tar.gz
        tar -xvzf NuSMV-2.6.0-linux64.tar.gz
        export PATH=$PWD/NuSMV-2.6.0-Linux/bin:$PATH
        mvn -B compile --file pom.xml
        mvn -B package --file pom.xml
        find . -name "*.jar"
        md5sum code/extensions/asmeta.validator/asmeta.validator/dist/AsmetaV.jar
    # An example of how to pass artifacts between jobs is here:
    # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
    - name: Upload CLI binarier
      uses: actions/upload-artifact@v3
      with:
        name: Asmeta CLI Distribution
        # NOTE: are the new binaries in `target` directory?
        path:
          code/extensions/asmeta.validator/asmeta.validator/dist/AsmetaV.jar
          # code/extensions/asmeta.flattener/asmeta.flattener.cli/dist/AsmetaF.jar
          # code/extensions/asmetasmv/asmeta.smv/dist/AsmetaSMV.jar
          # code/extensions/asmeta.modeladvisor/asmeta.modeladvisor/dist/AsmetaMA.jar
          # code/extensions/asmeta.refprover/translatorToSMT/dist/AsmetaToSMT.jar
          # code/extensions/asmeta.refprover/refinementProof/dist/AsmetaRefProver.jar
          # code/core/asmeta.parser/asmeta.parser.cli/dist/AsmetaLc.jar
          # code/core/asmeta.simulator/asmeta.simulator.cli/dist/AsmetaS.jar
          # code/experimental/asmetal2cpp/asmetal2cpp_cli/dist/Asmeta2Cpp.jar
        # Keep only for one day now
        retention-days: 1
        

# Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
# - name: Update dependency graph
#   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
